### ISSUE TITLE
software pilot

### ISSUE THREAD

**Issue by wellsstephen** [wellsstephen/swells#5]
**Installation**
- [x] server1 - database binary installation
- [ ] server1 - other software binary installation
- [ ] server2 - database binary installation
- [ ] server2 - other software binary installation

**Configuration**
