### ISSUE TITLE
GoldenGate (OGG) cdc pilot - sandbox installation

### ISSUE THREAD

**Issue by wellsstephen** [wellsstephen/swells#6]
**GoldenGate server**
- [ ] AWS server1 binary install - Oracle Server 11g
- [ ] AWS server1 database creation - Oracle Server 11g (emulate CORP cdc source)
- [ ] AWS server1 binary install - Oracle GoldenGate (emulate CORP cdc source)

**Vet360 cdc stage database server**
- [ ] AWS server2 binary install - Oracle Server 12c
- [ ] AWS server2 database creation - Oracle Server 12c (emulate vet360 cdc target)
